### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by ard333** [spring-projects-experimental/spring-graal-feature#1]
Hi
I tried to compile vanilla-jpa sample project on my 8GB Ubuntu (7.5GB free) but got this error message

> java.lang.OutOfMemoryError: GC overhead limit exceeded

**GraalVM version**
>openjdk version "1.8.0_222"
>OpenJDK Runtime Environment (build 1.8.0_222-20190711120915.buildslave.jdk8u-src-tar--b08)
>OpenJDK 64-Bit GraalVM CE 19.2.0 (build 25.222-b08-jvmci-19.2-b02, mixed mode)

Is there anything I missed? or is there a minimum of RAM for building native image in this project?

**Comment by aclement** [comment]
Graal is keen to eat memory and vanilla-jpa is a sample that takes a particularly long time even on my 32G macbook pro. Do the simple ones compile? (Like commandlinerunner - this simplest). 

Per the docs at https://www.graalvm.org/docs/reference-manual/aot-compilation/
```
Another prerequisite to consider is the maximum heap size. Physical memory for running a JVM-based application may be insufficient to build a native image. 
```

I just tried 16G by adding `-J-Xmx16g` to the native-image call in compile.sh - that was OK but took a while (536s). Then I tried it again with 8g slower again at 1449s. Finally at 6g i got out of memory: `Exception in thread "RMI TCP Connection(idle)" java.lang.OutOfMemoryError: GC overhead limit exceeded`

According to those docs it will try to use 80% of your physical RAM. So if you have 8 it'll be trying with 6ish. You could giving it more via that `-J-Xmx8g` in the compile.sh, that might help (but it'll take a while)

**Comment by ard333** [comment]
For commandlinerunner it took ~87s on my laptop.

Yes, I also tried `-J-Xmx7g` at that time for vanilla-jpa, I think I have to build it on another machine. 😅

Thank you very much for the explanation @aclement
